[tools]
rust = { version = "stable", components = "rust-analyzer" }
zig = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-llvm-cov" = "latest"

[tasks]
build = { run = "cargo-zigbuild build" }
run = { run = "cargo-zigbuild run" }
test = { run = "cargo-zigbuild test" }
